#!/bin/bash
# Setup Wazuh agent on this machine for SIEM purposes.
# This is automatically generated by Terraform.
WAZUH_MANAGER_IP="${wazuh_manager_ip}"
WAZUH_MANAGER_PASSWORD="${wazuh_manager_password}"
if [ -z "$WAZUH_MANAGER_PASSWORD" ]
then
    /var/ossec/bin/agent-auth -m $WAZUH_MANAGER_IP
else
    /var/ossec/bin/agent-auth -m $WAZUH_MANAGER_IP -P $WAZUH_MANAGER_PASSWORD
fi
systemctl start wazuh-agent